#端口配置
server:
  port: 8081


#页面缓存配置
spring:
  #配置模板无缓存
  thymeleaf:
    cache: false
  #配置Solr工程地址(通过该工程来进行搜索服务)
  data:
    solr:
      host: http://47.112.22.169:8080/solr
  #配置消息中间件RabbitMQ(用于生成商品详情静态页面)
  rabbitmq:
    host: 47.112.22.169
    username: wan
    password: 83740932
    port: 5672
    virtual-host: /wan



#配置dubbo
dubbo:
  #注册名
  application:
    name: shop_recept
  #注册地址
  registry:
    address: zookeeper://47.112.22.169:2181